#!/usr/bin/env python3
"""
fig3_delta_rho.py
=================
Figure 3 — Differential charge density (Δρ) processing script.

Δρ = ρ(SnO₂₋ₓ) − ρ(SnO₂ pristine)
     Yellow isosurface (+) = charge accumulation at Sn²⁺ sites adjacent to Vo
     Cyan   isosurface (−) = charge depletion at Vo site

This script:
  1. Subtracts pristine cube from doped cube (Python path)
  2. Saves Δρ cube files ready for VESTA 3D rendering
  3. Generates a 2D cross-section slice plot of Δρ for quick inspection
     and as a manuscript-ready figure if VESTA is unavailable

For the final manuscript figure, VESTA 3D rendering is strongly recommended.
See VESTA_rendering_guide below.

Output:
  delta_rho_1to1.cube   ← open in VESTA, render isosurface ±0.005 e/Å³
  delta_rho_2to1.cube   ← open in VESTA, render isosurface ±0.005 e/Å³
  fig3_delta_rho_slice.png / .pdf   ← 2D slice for quick check
"""

import sys, os, re
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.colors import TwoSlopeNorm

sys.path.insert(0, os.path.dirname(__file__))
from plot_config import apply_style, COLORS, DOUBLE_COL, cm2in

apply_style()

BASE = os.path.join(os.path.dirname(__file__), '..')

CUBE_FILES = {
    'pristine' : f'{BASE}/pristine/pp/SnO2_pristine_charge.cube',
    '1to1'     : f'{BASE}/ratio_1to1/pp/SnO2_1to1_charge.cube',
    '2to1'     : f'{BASE}/ratio_2to1/pp/SnO2_2to1_charge.cube',
}

# ── Cube file reader ────────────────────────────────────────────────────────

def read_cube(path):
    """
    Parse a Gaussian cube file.
    Returns: atoms(list), origin(array), cell(3x3 array), data(3D array)
    Units: Bohr internally; data in e/Bohr³
    """
    if not os.path.exists(path):
        return None, None, None, None

    with open(path) as f:
        lines = f.readlines()

    # Lines 1-2: comments
    # Line 3: natoms + origin
    parts   = lines[2].split()
    natoms  = int(parts[0])
    origin  = np.array([float(x) for x in parts[1:4]])

    # Lines 4-6: grid dimensions and vectors
    grids = []
    vecs  = []
    for i in range(3, 6):
        p = lines[i].split()
        grids.append(int(p[0]))
        vecs.append([float(x) for x in p[1:4]])
    n1, n2, n3 = grids
    cell = np.array(vecs)   # each row = lattice vector / grid_points

    # Lines 7 to 7+natoms: atom positions
    atoms = []
    for i in range(6, 6 + natoms):
        atoms.append(lines[i].split())

    # Remaining lines: volumetric data
    data_vals = []
    for line in lines[6 + natoms:]:
        data_vals.extend([float(x) for x in line.split()])

    data = np.array(data_vals).reshape(n1, n2, n3)
    return atoms, origin, cell, data


def write_cube(path, atoms, origin, cell, data):
    """Write a cube file."""
    n1, n2, n3 = data.shape
    with open(path, 'w') as f:
        f.write('Differential charge density\n')
        f.write('Generated by fig3_delta_rho.py\n')
        f.write(f'{len(atoms):5d} {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n')
        for i, (n, v) in enumerate(zip([n1, n2, n3], cell)):
            f.write(f'{n:5d} {v[0]:12.6f} {v[1]:12.6f} {v[2]:12.6f}\n')
        for atom in atoms:
            f.write('  '.join(atom) + '\n')
        flat = data.flatten()
        for i in range(0, len(flat), 6):
            chunk = flat[i:i+6]
            f.write(''.join(f'{v:13.5e}' for v in chunk) + '\n')
    print(f"  Written: {path}")


def make_demo_cube(n=40):
    """Generate a demo Δρ cube for testing."""
    x = np.linspace(0, 1, n)
    X, Y, Z = np.meshgrid(x, x, x, indexing='ij')
    # Two accumulation centres (Sn²⁺ sites) and one depletion centre (Vo)
    r1 = np.sqrt((X-0.3)**2 + (Y-0.3)**2 + (Z-0.5)**2)
    r2 = np.sqrt((X-0.7)**2 + (Y-0.7)**2 + (Z-0.5)**2)
    r3 = np.sqrt((X-0.5)**2 + (Y-0.5)**2 + (Z-0.5)**2)
    data = 0.03 * np.exp(-r1**2 / 0.01) + 0.03 * np.exp(-r2**2 / 0.01) \
         - 0.025 * np.exp(-r3**2 / 0.008)
    cell   = np.eye(3) * 9.474 / 0.529177 / n    # Bohr
    origin = np.zeros(3)
    atoms  = [['50', '0', f'{9.474*x:.6f}', '0.000', '0.000'] for x in [0.3, 0.7]]
    return atoms, origin, cell, data


# ── main computation ────────────────────────────────────────────────────────

def compute_delta_rho(doped_key):
    """Subtract pristine from doped cube; return delta_rho array."""
    _, _, cell_p, rho_p = read_cube(CUBE_FILES['pristine'])
    _, orig, cell_d, rho_d = read_cube(CUBE_FILES[doped_key])

    if rho_p is None or rho_d is None:
        print(f"  Cube files not found — using DEMO data for {doped_key}")
        return *make_demo_cube()[:4], make_demo_cube()[4] if False else (
            *make_demo_cube(), )

    # Align grids: pad/trim pristine to match doped if needed
    if rho_p.shape != rho_d.shape:
        print(f"  WARNING: grid mismatch {rho_p.shape} vs {rho_d.shape}")
        min_shape = tuple(min(a, b) for a, b in zip(rho_p.shape, rho_d.shape))
        rho_p = rho_p[:min_shape[0], :min_shape[1], :min_shape[2]]
        rho_d = rho_d[:min_shape[0], :min_shape[1], :min_shape[2]]

    delta = rho_d - rho_p
    return orig, cell_d, delta


# ── 2D slice plot ────────────────────────────────────────────────────────────

def plot_slice(ax, delta_rho, cell, title, panel_letter, atoms_doped=None):
    """Plot a 2D z-midplane slice of Δρ."""
    n3    = delta_rho.shape[2]
    slice_2d = delta_rho[:, :, n3 // 2]

    # Convert grid to Ångström
    a_ang = np.linalg.norm(cell[0]) * 0.529177 * delta_rho.shape[0]
    b_ang = np.linalg.norm(cell[1]) * 0.529177 * delta_rho.shape[1]

    vmax  = np.percentile(np.abs(slice_2d), 99)
    norm  = TwoSlopeNorm(vmin=-vmax, vcenter=0, vmax=vmax)

    im = ax.imshow(slice_2d.T, origin='lower', aspect='equal',
                   extent=[0, a_ang, 0, b_ang],
                   cmap='RdBu_r', norm=norm, interpolation='bicubic')

    cbar = plt.colorbar(im, ax=ax, shrink=0.8, pad=0.02)
    cbar.set_label('Δρ (e/Bohr³)', fontsize=7)
    cbar.ax.tick_params(labelsize=6)

    ax.set_xlabel('x (Å)', fontsize=8)
    ax.set_ylabel('y (Å)', fontsize=8)
    ax.set_title(f'({panel_letter}) {title}', fontsize=9, fontweight='bold')

    # Annotate charge accumulation / depletion
    ax.text(0.02, 0.97, '+ accumulation (Sn²⁺)',
            transform=ax.transAxes, fontsize=7, va='top',
            color='#C0392B')
    ax.text(0.02, 0.89, '− depletion (Vo site)',
            transform=ax.transAxes, fontsize=7, va='top',
            color='#2980B9')


# ── figure assembly ──────────────────────────────────────────────────────────

print("Computing Δρ = ρ(doped) − ρ(pristine)...")

results = {}
for key in ('1to1', '2to1'):
    path_p  = CUBE_FILES['pristine']
    path_d  = CUBE_FILES[key]

    if os.path.exists(path_p) and os.path.exists(path_d):
        atoms_p, _, _, rho_p = read_cube(path_p)
        atoms_d, orig, cell, rho_d = read_cube(path_d)

        if rho_p.shape != rho_d.shape:
            s = tuple(min(a, b) for a, b in zip(rho_p.shape, rho_d.shape))
            rho_p = rho_p[:s[0], :s[1], :s[2]]
            rho_d = rho_d[:s[0], :s[1], :s[2]]

        delta = rho_d - rho_p
        results[key] = (atoms_d, orig, cell, delta)

        # Write Δρ cube for VESTA
        out_cube = os.path.join(os.path.dirname(__file__),
                                f'delta_rho_{key}.cube')
        write_cube(out_cube, atoms_d, orig, cell, delta)
    else:
        print(f"  Cube files missing for {key} — using demo data")
        demo = make_demo_cube()
        results[key] = demo[:4]   # atoms, origin, cell, data (demo)

fig, axes = plt.subplots(1, 2, figsize=(DOUBLE_COL, cm2in(9)))
fig.subplots_adjust(wspace=0.32, left=0.09, right=0.97,
                    top=0.90, bottom=0.12)

titles  = {'1to1': 'SnO₂₋ₓ 1:1  (2 Vo, Vo = 12.5%)',
           '2to1': 'SnO₂₋ₓ 2:1  (3 Vo, Vo = 18.75%)'}
letters = {'1to1': 'a', '2to1': 'b'}

for ax, key in zip(axes, ('1to1', '2to1')):
    atoms_d, orig, cell, delta = results[key]
    plot_slice(ax, delta, cell, titles[key], letters[key])

fig.suptitle('Differential Charge Density  Δρ = ρ(SnO₂₋ₓ) − ρ(SnO₂)',
             fontsize=10, fontweight='bold', y=0.98)

# Note box
fig.text(0.5, 0.01,
         '⚠  For publication: render delta_rho_*.cube in VESTA '
         '(isosurface ±0.005 e/Å³; yellow = +, cyan = −)',
         ha='center', fontsize=7, color='0.4', style='italic')

out_dir = os.path.dirname(__file__)
for ext in ('png', 'pdf'):
    path = os.path.join(out_dir, f'fig3_delta_rho_slice.{ext}')
    fig.savefig(path)
    print(f"Saved: {path}")
plt.close()

# ── VESTA rendering guide ────────────────────────────────────────────────────
VESTA_GUIDE = """
VESTA Rendering Guide for Δρ Isosurfaces
==========================================
1. Open VESTA → File → Open → select delta_rho_1to1.cube
2. Objects → Isosurfaces:
     Surface 1: Level = +0.005 e/Å³  Colour = yellow (255,200,0)  Opacity = 0.7
     Surface 2: Level = -0.005 e/Å³  Colour = cyan   (0,180,220)  Opacity = 0.7
3. Style → Atoms: Sn = grey sphere (r=0.8Å), O = red sphere (r=0.5Å)
4. Mark Vo sites with empty sphere (r=0.3Å, colour=white/outlined)
5. Rotate to show both Vo sites clearly
6. Export: File → Export Raster Image → PNG, 300 DPI, 1800×1200 px
7. Repeat for delta_rho_2to1.cube
8. Arrange both images side-by-side in figure with labels (a) and (b)

Adjust isosurface level if needed:
  - Too much noise: increase threshold to ±0.008 e/Å³
  - Too sparse:     decrease to ±0.003 e/Å³
"""
print(VESTA_GUIDE)

guide_path = os.path.join(os.path.dirname(__file__), 'VESTA_rendering_guide.txt')
with open(guide_path, 'w') as f:
    f.write(VESTA_GUIDE)
print(f"Guide saved: {guide_path}")
